apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g23v7b5og-java-springboot
  janus-idp.io/tekton: g23v7b5og-java-springboot
  backstage.io/kubernetes-id: g23v7b5og-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g23v7b5og-java-springboot
resources:
- deployment.yaml
- route.yaml
- service.yaml
